services:
    dev:
      container_name: main
      extends:
        file: docker/compose_fragments/service_base.yml
        service: secret_service
      image: main
      build:
        context: .
        dockerfile: docker/node.dev.Dockerfile
      volumes:
        - $PWD/scripts:/usr/bin/app/scripts
        - $PWD/generated:/usr/bin/app/generated
        - $PWD/src:/usr/bin/app/src
      command: yarn start:dev

    prod:
      container_name: main
      extends:
        file: docker/compose_fragments/service_base.yml
        service: secret_service
      image: main
      build:
        context: .
        dockerfile: docker/node.Dockerfile
      volumes:
        - $PWD/scripts:/usr/bin/app/scripts
        - $PWD/generated:/usr/bin/app/generated
      command:
        - node ./scripts/build/generateDockerSecretTypes.js

